[package]
name = "aoc"
version = "0.1.0"
authors = ["Gorelov Ruslan <r.gorelov@s7.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
fancy-regex = "0.2.0"
serde_json = "1.0"